### ISSUE TITLE
About double-quotes process

### ISSUE THREAD

**Issue by zombic** [roman-kashitsyn/text-csv#8]
When double-quotes are used to enclose fields without comma, the double-quiotes is not escaped by preceding it with another double quote.
I changed ostream.hpp line 149 and append quote_ into special_symbols. This problem is resolved.
I feel this is probably a program bug. I hope you can pay attention to it.

**Comment by roman-kashitsyn** [comment]
Hi @zombic,

Thank you very much for reporting this issue. Can you please provide a small piece of data you used to reproduce this issue? Just (1) the value of the field, (2) expected CSV encoding, and (3) the actual CSV encoding produced by the library. I will create a test case using this dataset which will help me to reproduce (and fix) the issue and to avoid regressions in future.
Thank you very much in advance.

**Comment by roman-kashitsyn** [comment]
It looks like the problem is reproducible with the following data:

Input: `""Double Quotes""`
Expected Encoding `"""""Double Quotes"""""`
Actual Encoding: `""Double Quotes""`

**Comment by zombic** [comment]
Yes.
Just have " but don't include ,
Like:
Input: aaa,",bbb
Expected Encoding aaa,"",bbb
Actual Encoding: aaa,",bbb

**Comment by roman-kashitsyn** [comment]
It looks like the fix you've proposed works just fine.

> Input: aaa,",bbb
> Expected Encoding aaa,"",bbb
> Actual Encoding: aaa,",bbb

I think that correct encoding for `aaa,",bbb` is `aaa,"""",bbb` (4 quotes). I will add your example to the test cases.

**Comment by zombic** [comment]
Yea,you are right. I was stupid. Haha...
