### ISSUE TITLE
Header row returned wrong index 

### ISSUE THREAD

**Issue by huanghugo** [roman-kashitsyn/text-csv#9]
````
text::csv::header header(csvStream);
std::size_t index = header.index_of("some_key_string");
````

if "some_key_string" not exist, the returned index is not npos but some incorrect value.

**Comment by roman-kashitsyn** [comment]
Thank you very much for reporting this issue! I'll submit the fix for this problem soon.

**Comment by huanghugo** [comment]
Great, thank you very much !
